source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target 'LifeCalendar' do

pod 'AFNetworking','~> 2.6.3'
pod 'Mantle' ,'~> 1.5.6'
pod 'FMDB'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UMengAnalytics'
pod 'UMengFeedback'
pod 'Masonry'
pod 'DateTools'


end